version: '3'
services:
    app:
        image: node:latest
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
        networks:
            - agner-network
        working_dir: /usr/app
        command: bash -c "npm install && npm start"
        depends_on:
            - db
    db:
        image: mongo:latest
        container_name: mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        networks:
            - agner-network

networks:
    agner-network:
        driver: bridge          
